volumes:
  wp_vol:
  db_vol:

networks:
  my_network:

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network


  wordpress:
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    restart: on-failure
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network


  mariadb:
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - my_network