volumes:
  wp_vol:
  db_vol:

networks:
  my_network:

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network


  wordpress:
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_ADMIN_LOGIN
      - WP_ADMIN_EMAIL
      - WP_ADMIN_PASSWORD
      - WP_AUTHOR_LOGIN
      - WP_AUTHOR_EMAIL
      - WP_AUTHOR_PASSWORD


  mariadb:
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - my_network
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD