volumes:
  wp_vol:
  db_vol:

networks:
  my_network:

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network


  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network



  mariadb:
    container_name: mariadb
    env_file:
      - .env
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - my_network

    
  adminer:
    container_name: adminer
    build: ./requirements/Adminer
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - my_network


  redis:
    container_name: redis
    build: ./requirements/redis
    restart: on-failure
    networks:
      - my_network

  containerization:
    container_name: containerization
    build: ./requirements/containerization
    ports:
      - 3000:3000
    restart: on-failure
    networks:
      - my_network


  # portainer:
  #   container_name: portainer
  #   build:
  #     context: ./requirements/portainer
  #     args:
  #       - PORTAINER_PASS=${PORTAINER_PASS:-def}
  #   env_file : .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - my_network
  #   depends_on:
  #     - wordpress
  #   restart: always