volumes:
  wp_vol:
  db_vol:

networks:
  my_network:

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network


  wordpress:
    env_file:
      - .env
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wp_vol:/var/www/html
    networks:
      - my_network



  mariadb:
    env_file:
      - .env
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - my_network

    
  adminer:
    build: ./requirements/Adminer
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - my_network