volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/momeaizi/data/wordpress
      o: bind

  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/momeaizi/data/mariadb
      o: bind

  redis_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/momeaizi/data/redis
      o: bind

networks:
  my_network:

services:
  nginx:
    container_name: nginx
    image: nginx:v1337.0
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - my_network


  wordpress:
    container_name: wordpress
    image: wordpress:v1337.0
    env_file:
      - .env
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - my_network



  mariadb:
    container_name: mariadb
    image: mariadb:v1337.0
    env_file:
      - .env
    build: ./requirements/mariadb
    restart: on-failure
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - my_network

    
  adminer:
    container_name: adminer
    image: adminer:v1337.0
    build: ./requirements/bonus/Adminer
    ports:
      - 8080:8080
    restart: on-failure
    networks:
      - my_network
  
  ftp:
    container_name: ftp
    image: ftp:v1337.0
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    ports:
      - 20:20
      - 21:21
      - 5000-5010:5000-5010
    restart: on-failure
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - my_network


  redis:
    container_name: redis
    image: redis:v1337.0
    build: ./requirements/bonus/redis
    restart: on-failure
    volumes:
      - redis_vol:/var/lib/redis
    networks:
      - my_network


  containerization:
    container_name: containerization
    image: containerization:v1337.0
    build: ./requirements/bonus/containerization
    ports:
      - 3000:3000
    restart: on-failure
    networks:
      - my_network


  portainer:
    container_name: portainer
    image: portainer:v1337.0
    build: ./requirements/bonus/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    restart: on-failure
    networks:
      - my_network
